// OpenCV CPU baseline features

#define CV_CPU_COMPILE_SSE 1
#define CV_CPU_BASELINE_COMPILE_SSE 1

#define CV_CPU_COMPILE_SSE2 1
#define CV_CPU_BASELINE_COMPILE_SSE2 1

#define CV_CPU_BASELINE_FEATURES 0
//    , CV_CPU_SSE \
//    , CV_CPU_SSE2 \


// OpenCV supported CPU dispatched features

#define CV_CPU_DISPATCH_COMPILE_SSE4_1 0
#define CV_CPU_DISPATCH_COMPILE_SSE4_2 0
#define CV_CPU_DISPATCH_COMPILE_FP16 0
#define CV_CPU_DISPATCH_COMPILE_AVX 0


#define CV_CPU_DISPATCH_FEATURES 0
//    , CV_CPU_SSE4_1
//    , CV_CPU_SSE4_2
//    , CV_CPU_FP16
//    , CV_CPU_AVX
